namespace Mathematically.Quartermaster.Domain.Items
{
    /// <summary>
    ///     The PoE base item from the website.
    /// </summary>
    public enum BaseItemType
    {
        #region Weapons

        // Bow
        // Note ShortBow can be HeavyShortBow
        CrudeBow,
        ShortBow,
        LongBow,
        CompositeBow,
        RecurveBow,
        BoneBow,
        RoyalBow,
        DeathBow,
        GroveBow,
        CompoundBow,
        SniperBow,
        IvoryBow,
        HighbornBow,
        DecimationBow,
        ThicketBow,
        CitadelBow,
        RangerBow,
        MarakethBow,
        SpineBow,
        ImperialBow,
        HarbingerBow,

        // One hand axes
        RustedHatchet,
        JadeHatchet,
        BoardingAxe,
        Cleaver,
        BroadAxe,
        ArmingAxe,
        DecorativeAxe,
        SpectralAxe,
        JasparAxe,
        Tomahawk,
        WristChopper,
        WarAxe,
        ChestSplitter,
        CeremonialAxe,
        WraithAxe,
        KaruiAxe,
        SiegeAxe,
        ReaverAxe,
        VaalHatcher,
        RoyalAxe,
        InfernalAxe,

        // Two hand axes
        StoneAxe,
        JadeChopper,
        Woodsplitter,
        Poleaxe,
        DoubleAxe,
        GildedAxe,
        ShadowAxe,
        JasperChopper,
        TimberAxe,
        HeadsmanAxe,
        Labrys,
        NobleAxe,
        AbyssalAxe,
        KaruiChopper,
        SunderingAxe,
        EzomyteAxe,
        VaalAxe,
        DespotAxe,
        VoidAxe,

        // Two Hand Maces
        DriftwoodMaul,
        TribalMaul,
        Mallet,
        Sledgehammer,
        SpikedMaul,
        BrassMaul,
        FrightMaul,
        TotemicMaul,
        GreatMallet,
        Steelhead,
        SpinyMaul,
        PlatedMaul,
        DreadMaul,
        KaruiMaul,
        ColossusMallet,
        Piledriver,
        Meatgrinder,
        ImperialMaul,
        TerrorMaul,

        // Wands
        DriftwoodWand,
        GoatsHorn,
        CarvedWand,
        QuartzWand,
        SpiraledWand,
        SageWand,
        FaunsWand,
        EngravedWand,
        CrystalWand,
        SerpentWand,
        OmenWand,
        DemonsHorn,
        ImbuedWand,
        OpalWand,
        TornadoWand,
        ProphecyWand,

        // Claws
        NailedFist,
        SharktoothClaw,
        Awl,
        CatsPaw,
        Blinder,
        TimewornClaw,
        SparklingClaw,
        FrightClaw,
        ThresherClaw,
        Gouger,
        TigersPaw,
        GutRipper,
        PrehistoricClaw,
        NobleClaw,
        EagleClaw,
        GreatWhiteClaw,
        ThroatStabber,
        HelionsPaw,
        EyeGouger,
        VaalClaw,
        ImperialClaw,
        TerrorClaw,

        #endregion

        #region Armour

        // Boots
        IronGreaves,
        WoolShoes,
        RawhideBoots,
        ChainBoots,
        WrappedBoots,
        LeatherscaleBoots,
        SteelGreaves,
        VelvetSlippers,
        GoathideBoots,
        RingmailBoots,
        StrappedBoots,
        IronscaleBoots,
        DeerskinBoots,
        SilkSlippers,
        PlatedGreaves,
        ClaspedBoots,
        MeshBoots,
        BronzescaleBoots,
        ScholarBoots,
        ReinforcedGreaves,
        ShackledBoots,
        NubukBoots,
        SteelscaleBoots,
        RivetedBoots,
        AntiqueGreaves,
        SatinSlippers,
        EelskinBoots,
        ZealotBoots,
        TrapperBoots,
        SerpentscaleBoots,
        SharskinBoots,
        SamiteSlippers,
        AncientGreaves,
        AmbushBoots,
        SoldierBoots,
        WyrmscaleBoots,
        ConjurerBoots,
        GoliathGreaves,
        ShagreenBoots,
        CarnalBoots,
        LegionBoots,
        HydrascaleBoots,
        ArcanistSlippers,
        StealthBoots,
        VaalGreaves,
        AssassinsBoots,
        CrusaderBoots,
        DragonscaleBoots,
        SorcererBoots,
        TitanGreaves,
        MurderBoots,
        SlinkBoots,

        #endregion

        #region Jewelry

        // Amulets
        PauaAmulet,
        CoralAmulet,
        AmberAmulet,
        LapisAmulet,
        JadeAmulet,
        GoldAmulet,
        AgateAmulet,
        CitrineAmulet,
        TurqoiseAmulet,
        OnyxAmulet,

        // Belts
        ChainBelt,
        RusticSash,
        HeavyBelt,
        LeatherBelt,
        GoldenObi,
        ClothBelt,
        StudiedBelt,

        // Rings
        // Note there are really three types of twostone depending on elements, although hopefully can avoid that complexity.
        IronRing,
        CoralRing,
        PauaRing,
        RubyRing,
        GoldRing,
        TopazRing,
        SapphireRing,
        TwoStoneRing,
        MoonstoneRing,
        DiamondRing,
        PrismaticRing,
        AmethystRing,
        UnsetRing,

        #endregion
    }
}